namespace DandD.Home
{
    internal class SkillStrengthMult
    {
        public int Skill1 { get; set; } = 324;
        public int Skill2 { get; set;} = 23;
        public int Skill3 { get; set; } = 325; 
        public int Skill4 { get; set; } = 112;
        public int Skill5 { get; set; } = 345;
        public int Skill6 { get; set; } = 324;
        public int Skill7 { get; set; } = 12;
        public int Skill8 { get; set; } = 43;
        public int Skill9 { get; set; } = 46;
        public int Skill10 { get; set; } = 2;
        public int Skill11 { get; set; } = 643;
        public int Skill12 { get; set; } = 345;
        public int Skill13 { get; set; } = 23;
        public int Skill14 { get; set; } = 43;
        public int Skill15 { get; set; } = 43;
        public int Skill16 { get; set; } = 23;
        public int Skill17 { get; set; } = 42;
        public int Skill18 { get; set; } = 235;
        public int Skill19 { get; set; } = 234;
        public int Skill20 { get; set; } = 1;
        public int Skill21 { get; set; } = 1;
        public int Skill22 { get; set; } = 1;
        public int Skill23 { get; set; } = 1;
        public int Skill24 { get; set; } = 1;
        public int Skill25 { get; set; } = 1;
        public int Skill26 { get; set; } = 1;
        public int Skill27 { get; set; } = 1;
        public int Skill28 { get; set; } = 1;
        public int Skill29 { get; set; } = 1;
        public int Skill30 { get; set; } = 1;
        public int Skill31 { get; set; } = 1;
        public int Skill32 { get; set; } = 1;
        public int Skill33 { get; set; } = 1;
        public int Skill34 { get; set; } = 1;
        public int Skill35 { get; set; } = 1;
        public int Skill36 { get; set; } = 1;
        public int Skill37 { get; set; } = 1;
        public int Skill38 { get; set; } = 1;
        public int Skill39 { get; set; } = 1;
        public int Skill40 { get; set; } = 1;
        public int Skill41 { get; set; } = 1;
        public int Skill42 { get; set; } = 1;
        public int Skill43 { get; set; } = 1;
        public int Skill44 { get; set; } = 1;
        public int Skill45 { get; set; } = 1;
        public int Skill46 { get; set; } = 1;
        public int Skill47 { get; set; } = 1;
        public int Skill48 { get; set; } = 1;
        public int Skill49 { get; set; } = 1;
        public int Skill50 { get; set; } = 1;
        public int Skill51 { get; set; } = 1;
        public int Skill52 { get; set; } = 1;
        public int Skill53 { get; set; } = 1;
        public int Skill54 { get; set; } = 1;
        public int Skill55 { get; set; } = 1;
        public int Skill56 { get; set; } = 1;
        public int Skill57 { get; set; } = 1;
        public int Skill58 { get; set; } = 1;
        public int Skill59 { get; set; } = 1;
        public int Skill60 { get; set; } = 1;
        public int Skill61 { get; set; } = 1;
        public int Skill62 { get; set; } = 1;
        public int Skill63 { get; set; } = 1;
        public int Skill64 { get; set; } = 1;
        public int Skill65 { get; set; } = 1;
        public int Skill66 { get; set; } = 1;
        public int Skill67 { get; set; } = 1;
        public int Skill68 { get; set; } = 1;
        public int Skill69 { get; set; } = 1;
        public int Skill70 { get; set; } = 1;
        public int Skill71 { get; set; } = 1;
        public int Skill72 { get; set; } = 1;
        public int Skill73 { get; set; } = 1;
        public int Skill74 { get; set; } = 1;
        public int Skill75 { get; set; } = 1;
        public int Skill76 { get; set; } = 1;
        public int Skill77 { get; set; } = 1;
        public int Skill78 { get; set; } = 1;
        public int Skill79 { get; set; } = 1;
        public int Skill80 { get; set; } = 1;
        public int Skill81 { get; set; } = 1;
        public int Skill82 { get; set; } = 1;
        public int Skill83 { get; set; } = 1;
        public int Skill84 { get; set; } = 1;
        public int Skill85 { get; set; } = 1;
        public int Skill86 { get; set; } = 1;
        public int Skill87 { get; set; } = 1;
        public int Skill88 { get; set; } = 1;
    }   

    internal class SkillConstitutionMult
    {
        public int Skill1 { get; set; } = 1;
        public int Skill2 { get; set; } = 1;
        public int Skill3 { get; set; } = 1;
        public int Skill4 { get; set; } = 1;
        public int Skill5 { get; set; } = 1;
        public int Skill6 { get; set; } = 1;
        public int Skill7 { get; set; } = 1;
        public int Skill8 { get; set; } = 1;
        public int Skill9 { get; set; } = 1;
        public int Skill10 { get; set; } = 1;
        public int Skill11 { get; set; } = 1;
        public int Skill12 { get; set; } = 1;
        public int Skill13 { get; set; } = 1;
        public int Skill14 { get; set; } = 1;
        public int Skill15 { get; set; } = 1;
        public int Skill16 { get; set; } = 1;
        public int Skill17 { get; set; } = 1;
        public int Skill18 { get; set; } = 1;
        public int Skill19 { get; set; } = 1;
        public int Skill20 { get; set; } = 1;
        public int Skill21 { get; set; } = 1;
        public int Skill22 { get; set; } = 1;
        public int Skill23 { get; set; } = 1;
        public int Skill24 { get; set; } = 1;
        public int Skill25 { get; set; } = 1;
        public int Skill26 { get; set; } = 1;
        public int Skill27 { get; set; } = 1;
        public int Skill28 { get; set; } = 1;
        public int Skill29 { get; set; } = 1;
        public int Skill30 { get; set; } = 1;
        public int Skill31 { get; set; } = 1;
        public int Skill32 { get; set; } = 1;
        public int Skill33 { get; set; } = 1;
        public int Skill34 { get; set; } = 1;
        public int Skill35 { get; set; } = 1;
        public int Skill36 { get; set; } = 1;
        public int Skill37 { get; set; } = 1;
        public int Skill38 { get; set; } = 1;
        public int Skill39 { get; set; } = 1;
        public int Skill40 { get; set; } = 1;
        public int Skill41 { get; set; } = 1;
        public int Skill42 { get; set; } = 1;
        public int Skill43 { get; set; } = 1;
        public int Skill44 { get; set; } = 1;
        public int Skill45 { get; set; } = 1;
        public int Skill46 { get; set; } = 1;
        public int Skill47 { get; set; } = 1;
        public int Skill48 { get; set; } = 1;
        public int Skill49 { get; set; } = 1;
        public int Skill50 { get; set; } = 1;
        public int Skill51 { get; set; } = 1;
        public int Skill52 { get; set; } = 1;
        public int Skill53 { get; set; } = 1;
        public int Skill54 { get; set; } = 1;
        public int Skill55 { get; set; } = 1;
        public int Skill56 { get; set; } = 1;
        public int Skill57 { get; set; } = 1;
        public int Skill58 { get; set; } = 1;
        public int Skill59 { get; set; } = 1;
        public int Skill60 { get; set; } = 1;
        public int Skill61 { get; set; } = 1;
        public int Skill62 { get; set; } = 1;
        public int Skill63 { get; set; } = 1;
        public int Skill64 { get; set; } = 1;
        public int Skill65 { get; set; } = 1;
        public int Skill66 { get; set; } = 1;
        public int Skill67 { get; set; } = 1;
        public int Skill68 { get; set; } = 1;
        public int Skill69 { get; set; } = 1;
        public int Skill70 { get; set; } = 1;
        public int Skill71 { get; set; } = 1;
        public int Skill72 { get; set; } = 1;
        public int Skill73 { get; set; } = 1;
        public int Skill74 { get; set; } = 1;
        public int Skill75 { get; set; } = 1;
        public int Skill76 { get; set; } = 1;
        public int Skill77 { get; set; } = 1;
        public int Skill78 { get; set; } = 1;
        public int Skill79 { get; set; } = 1;
        public int Skill80 { get; set; } = 1;
        public int Skill81 { get; set; } = 1;
        public int Skill82 { get; set; } = 1;
        public int Skill83 { get; set; } = 1;
        public int Skill84 { get; set; } = 1;
        public int Skill85 { get; set; } = 1;
        public int Skill86 { get; set; } = 1;
        public int Skill87 { get; set; } = 1;
        public int Skill88 { get; set; } = 1;
    }

    internal class SkillDexterityMult
    {
        public int Skill1 { get; set; } = 1;
        public int Skill2 { get; set; } = 1;
        public int Skill3 { get; set; } = 1;
        public int Skill4 { get; set; } = 1;
        public int Skill5 { get; set; } = 1;
        public int Skill6 { get; set; } = 1;
        public int Skill7 { get; set; } = 1;
        public int Skill8 { get; set; } = 1;
        public int Skill9 { get; set; } = 1;
        public int Skill10 { get; set; } = 1;
        public int Skill11 { get; set; } = 1;
        public int Skill12 { get; set; } = 1;
        public int Skill13 { get; set; } = 1;
        public int Skill14 { get; set; } = 1;
        public int Skill15 { get; set; } = 1;
        public int Skill16 { get; set; } = 1;
        public int Skill17 { get; set; } = 1;
        public int Skill18 { get; set; } = 1;
        public int Skill19 { get; set; } = 1;
        public int Skill20 { get; set; } = 1;
        public int Skill21 { get; set; } = 1;
        public int Skill22 { get; set; } = 1;
        public int Skill23 { get; set; } = 1;
        public int Skill24 { get; set; } = 1;
        public int Skill25 { get; set; } = 1;
        public int Skill26 { get; set; } = 1;
        public int Skill27 { get; set; } = 1;
        public int Skill28 { get; set; } = 1;
        public int Skill29 { get; set; } = 1;
        public int Skill30 { get; set; } = 1;
        public int Skill31 { get; set; } = 1;
        public int Skill32 { get; set; } = 1;
        public int Skill33 { get; set; } = 1;
        public int Skill34 { get; set; } = 1;
        public int Skill35 { get; set; } = 1;
        public int Skill36 { get; set; } = 1;
        public int Skill37 { get; set; } = 1;
        public int Skill38 { get; set; } = 1;
        public int Skill39 { get; set; } = 1;
        public int Skill40 { get; set; } = 1;
        public int Skill41 { get; set; } = 1;
        public int Skill42 { get; set; } = 1;
        public int Skill43 { get; set; } = 1;
        public int Skill44 { get; set; } = 1;
        public int Skill45 { get; set; } = 1;
        public int Skill46 { get; set; } = 1;
        public int Skill47 { get; set; } = 1;
        public int Skill48 { get; set; } = 1;
        public int Skill49 { get; set; } = 1;
        public int Skill50 { get; set; } = 1;
        public int Skill51 { get; set; } = 1;
        public int Skill52 { get; set; } = 1;
        public int Skill53 { get; set; } = 1;
        public int Skill54 { get; set; } = 1;
        public int Skill55 { get; set; } = 1;
        public int Skill56 { get; set; } = 1;
        public int Skill57 { get; set; } = 1;
        public int Skill58 { get; set; } = 1;
        public int Skill59 { get; set; } = 1;
        public int Skill60 { get; set; } = 1;
        public int Skill61 { get; set; } = 1;
        public int Skill62 { get; set; } = 1;
        public int Skill63 { get; set; } = 1;
        public int Skill64 { get; set; } = 1;
        public int Skill65 { get; set; } = 1;
        public int Skill66 { get; set; } = 1;
        public int Skill67 { get; set; } = 1;
        public int Skill68 { get; set; } = 1;
        public int Skill69 { get; set; } = 1;
        public int Skill70 { get; set; } = 1;
        public int Skill71 { get; set; } = 1;
        public int Skill72 { get; set; } = 1;
        public int Skill73 { get; set; } = 1;
        public int Skill74 { get; set; } = 1;
        public int Skill75 { get; set; } = 1;
        public int Skill76 { get; set; } = 1;
        public int Skill77 { get; set; } = 1;
        public int Skill78 { get; set; } = 1;
        public int Skill79 { get; set; } = 1;
        public int Skill80 { get; set; } = 1;
        public int Skill81 { get; set; } = 1;
        public int Skill82 { get; set; } = 1;
        public int Skill83 { get; set; } = 1;
        public int Skill84 { get; set; } = 1;
        public int Skill85 { get; set; } = 1;
        public int Skill86 { get; set; } = 1;
        public int Skill87 { get; set; } = 1;
        public int Skill88 { get; set; } = 1;
    }

    internal class SkillIntelligenceMult
    {
        public int Skill1 { get; set; } = 1;
        public int Skill2 { get; set; } = 1;
        public int Skill3 { get; set; } = 1;
        public int Skill4 { get; set; } = 1;
        public int Skill5 { get; set; } = 1;
        public int Skill6 { get; set; } = 1;
        public int Skill7 { get; set; } = 1;
        public int Skill8 { get; set; } = 1;
        public int Skill9 { get; set; } = 1;
        public int Skill10 { get; set; } = 1;
        public int Skill11 { get; set; } = 1;
        public int Skill12 { get; set; } = 1;
        public int Skill13 { get; set; } = 1;
        public int Skill14 { get; set; } = 1;
        public int Skill15 { get; set; } = 1;
        public int Skill16 { get; set; } = 1;
        public int Skill17 { get; set; } = 1;
        public int Skill18 { get; set; } = 1;
        public int Skill19 { get; set; } = 1;
        public int Skill20 { get; set; } = 1;
        public int Skill21 { get; set; } = 1;
        public int Skill22 { get; set; } = 1;
        public int Skill23 { get; set; } = 1;
        public int Skill24 { get; set; } = 1;
        public int Skill25 { get; set; } = 1;
        public int Skill26 { get; set; } = 1;
        public int Skill27 { get; set; } = 1;
        public int Skill28 { get; set; } = 1;
        public int Skill29 { get; set; } = 1;
        public int Skill30 { get; set; } = 1;
        public int Skill31 { get; set; } = 1;
        public int Skill32 { get; set; } = 1;
        public int Skill33 { get; set; } = 1;
        public int Skill34 { get; set; } = 1;
        public int Skill35 { get; set; } = 1;
        public int Skill36 { get; set; } = 1;
        public int Skill37 { get; set; } = 1;
        public int Skill38 { get; set; } = 1;
        public int Skill39 { get; set; } = 1;
        public int Skill40 { get; set; } = 1;
        public int Skill41 { get; set; } = 1;
        public int Skill42 { get; set; } = 1;
        public int Skill43 { get; set; } = 1;
        public int Skill44 { get; set; } = 1;
        public int Skill45 { get; set; } = 1;
        public int Skill46 { get; set; } = 1;
        public int Skill47 { get; set; } = 1;
        public int Skill48 { get; set; } = 1;
        public int Skill49 { get; set; } = 1;
        public int Skill50 { get; set; } = 1;
        public int Skill51 { get; set; } = 1;
        public int Skill52 { get; set; } = 1;
        public int Skill53 { get; set; } = 1;
        public int Skill54 { get; set; } = 1;
        public int Skill55 { get; set; } = 1;
        public int Skill56 { get; set; } = 1;
        public int Skill57 { get; set; } = 1;
        public int Skill58 { get; set; } = 1;
        public int Skill59 { get; set; } = 1;
        public int Skill60 { get; set; } = 1;
        public int Skill61 { get; set; } = 1;
        public int Skill62 { get; set; } = 1;
        public int Skill63 { get; set; } = 1;
        public int Skill64 { get; set; } = 1;
        public int Skill65 { get; set; } = 1;
        public int Skill66 { get; set; } = 1;
        public int Skill67 { get; set; } = 1;
        public int Skill68 { get; set; } = 1;
        public int Skill69 { get; set; } = 1;
        public int Skill70 { get; set; } = 1;
        public int Skill71 { get; set; } = 1;
        public int Skill72 { get; set; } = 1;
        public int Skill73 { get; set; } = 1;
        public int Skill74 { get; set; } = 1;
        public int Skill75 { get; set; } = 1;
        public int Skill76 { get; set; } = 1;
        public int Skill77 { get; set; } = 1;
        public int Skill78 { get; set; } = 1;
        public int Skill79 { get; set; } = 1;
        public int Skill80 { get; set; } = 1;
        public int Skill81 { get; set; } = 1;
        public int Skill82 { get; set; } = 1;
        public int Skill83 { get; set; } = 1;
        public int Skill84 { get; set; } = 1;
        public int Skill85 { get; set; } = 1;
        public int Skill86 { get; set; } = 1;
        public int Skill87 { get; set; } = 1;
        public int Skill88 { get; set; } = 1;
    }

    internal class SkillWisdomMult
    {
        public int Skill1 { get; set; } = 1;
        public int Skill2 { get; set; } = 1;
        public int Skill3 { get; set; } = 1;
        public int Skill4 { get; set; } = 1;
        public int Skill5 { get; set; } = 1;
        public int Skill6 { get; set; } = 1;
        public int Skill7 { get; set; } = 1;
        public int Skill8 { get; set; } = 1;
        public int Skill9 { get; set; } = 1;
        public int Skill10 { get; set; } = 1;
        public int Skill11 { get; set; } = 1;
        public int Skill12 { get; set; } = 1;
        public int Skill13 { get; set; } = 1;
        public int Skill14 { get; set; } = 1;
        public int Skill15 { get; set; } = 1;
        public int Skill16 { get; set; } = 1;
        public int Skill17 { get; set; } = 1;
        public int Skill18 { get; set; } = 1;
        public int Skill19 { get; set; } = 1;
        public int Skill20 { get; set; } = 1;
        public int Skill21 { get; set; } = 1;
        public int Skill22 { get; set; } = 1;
        public int Skill23 { get; set; } = 1;
        public int Skill24 { get; set; } = 1;
        public int Skill25 { get; set; } = 1;
        public int Skill26 { get; set; } = 1;
        public int Skill27 { get; set; } = 1;
        public int Skill28 { get; set; } = 1;
        public int Skill29 { get; set; } = 1;
        public int Skill30 { get; set; } = 1;
        public int Skill31 { get; set; } = 1;
        public int Skill32 { get; set; } = 1;
        public int Skill33 { get; set; } = 1;
        public int Skill34 { get; set; } = 1;
        public int Skill35 { get; set; } = 1;
        public int Skill36 { get; set; } = 1;
        public int Skill37 { get; set; } = 1;
        public int Skill38 { get; set; } = 1;
        public int Skill39 { get; set; } = 1;
        public int Skill40 { get; set; } = 1;
        public int Skill41 { get; set; } = 1;
        public int Skill42 { get; set; } = 1;
        public int Skill43 { get; set; } = 1;
        public int Skill44 { get; set; } = 1;
        public int Skill45 { get; set; } = 1;
        public int Skill46 { get; set; } = 1;
        public int Skill47 { get; set; } = 1;
        public int Skill48 { get; set; } = 1;
        public int Skill49 { get; set; } = 1;
        public int Skill50 { get; set; } = 1;
        public int Skill51 { get; set; } = 1;
        public int Skill52 { get; set; } = 1;
        public int Skill53 { get; set; } = 1;
        public int Skill54 { get; set; } = 1;
        public int Skill55 { get; set; } = 1;
        public int Skill56 { get; set; } = 1;
        public int Skill57 { get; set; } = 1;
        public int Skill58 { get; set; } = 1;
        public int Skill59 { get; set; } = 1;
        public int Skill60 { get; set; } = 1;
        public int Skill61 { get; set; } = 1;
        public int Skill62 { get; set; } = 1;
        public int Skill63 { get; set; } = 1;
        public int Skill64 { get; set; } = 1;
        public int Skill65 { get; set; } = 1;
        public int Skill66 { get; set; } = 1;
        public int Skill67 { get; set; } = 1;
        public int Skill68 { get; set; } = 1;
        public int Skill69 { get; set; } = 1;
        public int Skill70 { get; set; } = 1;
        public int Skill71 { get; set; } = 1;
        public int Skill72 { get; set; } = 1;
        public int Skill73 { get; set; } = 1;
        public int Skill74 { get; set; } = 1;
        public int Skill75 { get; set; } = 1;
        public int Skill76 { get; set; } = 1;
        public int Skill77 { get; set; } = 1;
        public int Skill78 { get; set; } = 1;
        public int Skill79 { get; set; } = 1;
        public int Skill80 { get; set; } = 1;
        public int Skill81 { get; set; } = 1;
        public int Skill82 { get; set; } = 1;
        public int Skill83 { get; set; } = 1;
        public int Skill84 { get; set; } = 1;
        public int Skill85 { get; set; } = 1;
        public int Skill86 { get; set; } = 1;
        public int Skill87 { get; set; } = 1;
        public int Skill88 { get; set; } = 1;
    }

    internal class SkillCharismaMult
    {
        public int Skill1 { get; set; } = 1;
        public int Skill2 { get; set; } = 1;
        public int Skill3 { get; set; } = 1;
        public int Skill4 { get; set; } = 1;
        public int Skill5 { get; set; } = 1;
        public int Skill6 { get; set; } = 1;
        public int Skill7 { get; set; } = 1;
        public int Skill8 { get; set; } = 1;
        public int Skill9 { get; set; } = 1;
        public int Skill10 { get; set; } = 1;
        public int Skill11 { get; set; } = 1;
        public int Skill12 { get; set; } = 1;
        public int Skill13 { get; set; } = 1;
        public int Skill14 { get; set; } = 1;
        public int Skill15 { get; set; } = 1;
        public int Skill16 { get; set; } = 1;
        public int Skill17 { get; set; } = 1;
        public int Skill18 { get; set; } = 1;
        public int Skill19 { get; set; } = 1;
        public int Skill20 { get; set; } = 1;
        public int Skill21 { get; set; } = 1;
        public int Skill22 { get; set; } = 1;
        public int Skill23 { get; set; } = 1;
        public int Skill24 { get; set; } = 1;
        public int Skill25 { get; set; } = 1;
        public int Skill26 { get; set; } = 1;
        public int Skill27 { get; set; } = 1;
        public int Skill28 { get; set; } = 1;
        public int Skill29 { get; set; } = 1;
        public int Skill30 { get; set; } = 1;
        public int Skill31 { get; set; } = 1;
        public int Skill32 { get; set; } = 1;
        public int Skill33 { get; set; } = 1;
        public int Skill34 { get; set; } = 1;
        public int Skill35 { get; set; } = 1;
        public int Skill36 { get; set; } = 1;
        public int Skill37 { get; set; } = 1;
        public int Skill38 { get; set; } = 1;
        public int Skill39 { get; set; } = 1;
        public int Skill40 { get; set; } = 1;
        public int Skill41 { get; set; } = 1;
        public int Skill42 { get; set; } = 1;
        public int Skill43 { get; set; } = 1;
        public int Skill44 { get; set; } = 1;
        public int Skill45 { get; set; } = 1;
        public int Skill46 { get; set; } = 1;
        public int Skill47 { get; set; } = 1;
        public int Skill48 { get; set; } = 1;
        public int Skill49 { get; set; } = 1;
        public int Skill50 { get; set; } = 1;
        public int Skill51 { get; set; } = 1;
        public int Skill52 { get; set; } = 1;
        public int Skill53 { get; set; } = 1;
        public int Skill54 { get; set; } = 1;
        public int Skill55 { get; set; } = 1;
        public int Skill56 { get; set; } = 1;
        public int Skill57 { get; set; } = 1;
        public int Skill58 { get; set; } = 1;
        public int Skill59 { get; set; } = 1;
        public int Skill60 { get; set; } = 1;
        public int Skill61 { get; set; } = 1;
        public int Skill62 { get; set; } = 1;
        public int Skill63 { get; set; } = 1;
        public int Skill64 { get; set; } = 1;
        public int Skill65 { get; set; } = 1;
        public int Skill66 { get; set; } = 1;
        public int Skill67 { get; set; } = 1;
        public int Skill68 { get; set; } = 1;
        public int Skill69 { get; set; } = 1;
        public int Skill70 { get; set; } = 1;
        public int Skill71 { get; set; } = 1;
        public int Skill72 { get; set; } = 1;
        public int Skill73 { get; set; } = 1;
        public int Skill74 { get; set; } = 1;
        public int Skill75 { get; set; } = 1;
        public int Skill76 { get; set; } = 1;
        public int Skill77 { get; set; } = 1;
        public int Skill78 { get; set; } = 1;
        public int Skill79 { get; set; } = 1;
        public int Skill80 { get; set; } = 1;
        public int Skill81 { get; set; } = 1;
        public int Skill82 { get; set; } = 1;
        public int Skill83 { get; set; } = 1;
        public int Skill84 { get; set; } = 1;
        public int Skill85 { get; set; } = 1;
        public int Skill86 { get; set; } = 1;
        public int Skill87 { get; set; } = 1;
        public int Skill88 { get; set; } = 1;
    }

    public class SumSkillPoints
    {
        public static int SkillCheckPoint(int skill, string stat, int point)
        {
            var StrengthSkills = new SkillStrengthMult();
            var ConstitutionSkills = new SkillConstitutionMult();
            var DexteritySkills = new SkillDexterityMult();
            var IntelligenceSkills = new SkillIntelligenceMult();
            var WisdomSkills = new SkillWisdomMult();
            var CharismaSkills = new SkillCharismaMult();

            switch (stat)
            {
                case "Strength":
                    {
                        switch (skill)
                        {
                            case 0: return point * StrengthSkills.Skill1;
                            case 1: return point * StrengthSkills.Skill2;
                            case 2: return point * StrengthSkills.Skill3;
                            case 3: return point * StrengthSkills.Skill4;
                            case 4: return point * StrengthSkills.Skill5;
                            case 5: return point * StrengthSkills.Skill6;
                            case 6: return point * StrengthSkills.Skill7;
                            case 7: return point * StrengthSkills.Skill8;
                            case 8: return point * StrengthSkills.Skill9;
                            case 9: return point * StrengthSkills.Skill10;
                            case 10: return point * StrengthSkills.Skill11;
                            case 11: return point * StrengthSkills.Skill12;
                            case 12: return point * StrengthSkills.Skill13;
                            case 13: return point * StrengthSkills.Skill14;
                            case 14: return point * StrengthSkills.Skill15;
                            case 15: return point * StrengthSkills.Skill16;
                            case 16: return point * StrengthSkills.Skill17;
                            case 17: return point * StrengthSkills.Skill18;
                            case 18: return point * StrengthSkills.Skill19;
                            case 19: return point * StrengthSkills.Skill20;
                            case 20: return point * StrengthSkills.Skill21;
                            case 21: return point * StrengthSkills.Skill22;
                            case 22: return point * StrengthSkills.Skill23;
                            case 23: return point * StrengthSkills.Skill24;
                            case 24: return point * StrengthSkills.Skill25;
                            case 25: return point * StrengthSkills.Skill26;
                            case 26: return point * StrengthSkills.Skill27;
                            case 27: return point * StrengthSkills.Skill28;
                            case 28: return point * StrengthSkills.Skill29;
                            case 29: return point * StrengthSkills.Skill30;
                            case 30: return point * StrengthSkills.Skill31;
                            case 31: return point * StrengthSkills.Skill32;
                            case 32: return point * StrengthSkills.Skill33;
                            case 33: return point * StrengthSkills.Skill34;
                            case 34: return point * StrengthSkills.Skill35;
                            case 35: return point * StrengthSkills.Skill36;
                            case 36: return point * StrengthSkills.Skill37;
                            case 37: return point * StrengthSkills.Skill38;
                            case 38: return point * StrengthSkills.Skill39;
                            case 39: return point * StrengthSkills.Skill40;
                            case 40: return point * StrengthSkills.Skill41;
                            case 41: return point * StrengthSkills.Skill42;
                            case 42: return point * StrengthSkills.Skill43;
                            case 43: return point * StrengthSkills.Skill44;
                            case 44: return point * StrengthSkills.Skill45;
                            case 45: return point * StrengthSkills.Skill46;
                            case 46: return point * StrengthSkills.Skill47;
                            case 47: return point * StrengthSkills.Skill48;
                            case 48: return point * StrengthSkills.Skill49;
                            case 49: return point * StrengthSkills.Skill50;
                            case 50: return point * StrengthSkills.Skill51;
                            case 51: return point * StrengthSkills.Skill52;
                            case 52: return point * StrengthSkills.Skill53;
                            case 53: return point * StrengthSkills.Skill54;
                            case 54: return point * StrengthSkills.Skill55;
                            case 55: return point * StrengthSkills.Skill56;
                            case 56: return point * StrengthSkills.Skill57;
                            case 57: return point * StrengthSkills.Skill58;
                            case 58: return point * StrengthSkills.Skill59;
                            case 59: return point * StrengthSkills.Skill60;
                            case 60: return point * StrengthSkills.Skill61;
                            case 61: return point * StrengthSkills.Skill62;
                            case 62: return point * StrengthSkills.Skill63;
                            case 63: return point * StrengthSkills.Skill64;
                            case 64: return point * StrengthSkills.Skill65;
                            case 65: return point * StrengthSkills.Skill66;
                            case 66: return point * StrengthSkills.Skill67;
                            case 67: return point * StrengthSkills.Skill68;
                            case 68: return point * StrengthSkills.Skill69;
                            case 69: return point * StrengthSkills.Skill70;
                            case 70: return point * StrengthSkills.Skill71;
                            case 71: return point * StrengthSkills.Skill72;
                            case 72: return point * StrengthSkills.Skill73;
                            case 73: return point * StrengthSkills.Skill74;
                            case 74: return point * StrengthSkills.Skill75;
                            case 75: return point * StrengthSkills.Skill76;
                            case 76: return point * StrengthSkills.Skill77;
                            case 77: return point * StrengthSkills.Skill78;
                            case 78: return point * StrengthSkills.Skill79;
                            case 79: return point * StrengthSkills.Skill80;
                            case 80: return point * StrengthSkills.Skill81;
                            case 81: return point * StrengthSkills.Skill82;
                            case 82: return point * StrengthSkills.Skill83;
                            case 83: return point * StrengthSkills.Skill84;
                            case 84: return point * StrengthSkills.Skill85;
                            case 85: return point * StrengthSkills.Skill86;
                            case 86: return point * StrengthSkills.Skill87;
                            case 87: return point * StrengthSkills.Skill88;
                            default: return point;
                        }
                    }
                case "Constitution":
                    {
                        switch (skill)
                        {
                            case 0: return point * ConstitutionSkills.Skill1;
                            case 1: return point * ConstitutionSkills.Skill2;
                            case 2: return point * ConstitutionSkills.Skill3;
                            case 3: return point * ConstitutionSkills.Skill4;
                            case 4: return point * ConstitutionSkills.Skill5;
                            case 5: return point * ConstitutionSkills.Skill6;
                            case 6: return point * ConstitutionSkills.Skill7;
                            case 7: return point * ConstitutionSkills.Skill8;
                            case 8: return point * ConstitutionSkills.Skill9;
                            case 9: return point * ConstitutionSkills.Skill10;
                            case 10: return point * ConstitutionSkills.Skill11;
                            case 11: return point * ConstitutionSkills.Skill12;
                            case 12: return point * ConstitutionSkills.Skill13;
                            case 13: return point * ConstitutionSkills.Skill14;
                            case 14: return point * ConstitutionSkills.Skill15;
                            case 15: return point * ConstitutionSkills.Skill16;
                            case 16: return point * ConstitutionSkills.Skill17;
                            case 17: return point * ConstitutionSkills.Skill18;
                            case 18: return point * ConstitutionSkills.Skill19;
                            case 19: return point * ConstitutionSkills.Skill20;
                            case 20: return point * ConstitutionSkills.Skill21;
                            case 21: return point * ConstitutionSkills.Skill22;
                            case 22: return point * ConstitutionSkills.Skill23;
                            case 23: return point * ConstitutionSkills.Skill24;
                            case 24: return point * ConstitutionSkills.Skill25;
                            case 25: return point * ConstitutionSkills.Skill26;
                            case 26: return point * ConstitutionSkills.Skill27;
                            case 27: return point * ConstitutionSkills.Skill28;
                            case 28: return point * ConstitutionSkills.Skill29;
                            case 29: return point * ConstitutionSkills.Skill30;
                            case 30: return point * ConstitutionSkills.Skill31;
                            case 31: return point * ConstitutionSkills.Skill32;
                            case 32: return point * ConstitutionSkills.Skill33;
                            case 33: return point * ConstitutionSkills.Skill34;
                            case 34: return point * ConstitutionSkills.Skill35;
                            case 35: return point * ConstitutionSkills.Skill36;
                            case 36: return point * ConstitutionSkills.Skill37;
                            case 37: return point * ConstitutionSkills.Skill38;
                            case 38: return point * ConstitutionSkills.Skill39;
                            case 39: return point * ConstitutionSkills.Skill40;
                            case 40: return point * ConstitutionSkills.Skill41;
                            case 41: return point * ConstitutionSkills.Skill42;
                            case 42: return point * ConstitutionSkills.Skill43;
                            case 43: return point * ConstitutionSkills.Skill44;
                            case 44: return point * ConstitutionSkills.Skill45;
                            case 45: return point * ConstitutionSkills.Skill46;
                            case 46: return point * ConstitutionSkills.Skill47;
                            case 47: return point * ConstitutionSkills.Skill48;
                            case 48: return point * ConstitutionSkills.Skill49;
                            case 49: return point * ConstitutionSkills.Skill50;
                            case 50: return point * ConstitutionSkills.Skill51;
                            case 51: return point * ConstitutionSkills.Skill52;
                            case 52: return point * ConstitutionSkills.Skill53;
                            case 53: return point * ConstitutionSkills.Skill54;
                            case 54: return point * ConstitutionSkills.Skill55;
                            case 55: return point * ConstitutionSkills.Skill56;
                            case 56: return point * ConstitutionSkills.Skill57;
                            case 57: return point * ConstitutionSkills.Skill58;
                            case 58: return point * ConstitutionSkills.Skill59;
                            case 59: return point * ConstitutionSkills.Skill60;
                            case 60: return point * ConstitutionSkills.Skill61;
                            case 61: return point * ConstitutionSkills.Skill62;
                            case 62: return point * ConstitutionSkills.Skill63;
                            case 63: return point * ConstitutionSkills.Skill64;
                            case 64: return point * ConstitutionSkills.Skill65;
                            case 65: return point * ConstitutionSkills.Skill66;
                            case 66: return point * ConstitutionSkills.Skill67;
                            case 67: return point * ConstitutionSkills.Skill68;
                            case 68: return point * ConstitutionSkills.Skill69;
                            case 69: return point * ConstitutionSkills.Skill70;
                            case 70: return point * ConstitutionSkills.Skill71;
                            case 71: return point * ConstitutionSkills.Skill72;
                            case 72: return point * ConstitutionSkills.Skill73;
                            case 73: return point * ConstitutionSkills.Skill74;
                            case 74: return point * ConstitutionSkills.Skill75;
                            case 75: return point * ConstitutionSkills.Skill76;
                            case 76: return point * ConstitutionSkills.Skill77;
                            case 77: return point * ConstitutionSkills.Skill78;
                            case 78: return point * ConstitutionSkills.Skill79;
                            case 79: return point * ConstitutionSkills.Skill80;
                            case 80: return point * ConstitutionSkills.Skill81;
                            case 81: return point * ConstitutionSkills.Skill82;
                            case 82: return point * ConstitutionSkills.Skill83;
                            case 83: return point * ConstitutionSkills.Skill84;
                            case 84: return point * ConstitutionSkills.Skill85;
                            case 85: return point * ConstitutionSkills.Skill86;
                            case 86: return point * ConstitutionSkills.Skill87;
                            case 87: return point * ConstitutionSkills.Skill88;
                            default: return point;
                        }
                    }
                case "Dexterity":
                    {
                        switch (skill)
                        {
                            case 0: return point * DexteritySkills.Skill1;
                            case 1: return point * DexteritySkills.Skill2;
                            case 2: return point * DexteritySkills.Skill3;
                            case 3: return point * DexteritySkills.Skill4;
                            case 4: return point * DexteritySkills.Skill5;
                            case 5: return point * DexteritySkills.Skill6;
                            case 6: return point * DexteritySkills.Skill7;
                            case 7: return point * DexteritySkills.Skill8;
                            case 8: return point * DexteritySkills.Skill9;
                            case 9: return point * DexteritySkills.Skill10;
                            case 10: return point * DexteritySkills.Skill11;
                            case 11: return point * DexteritySkills.Skill12;
                            case 12: return point * DexteritySkills.Skill13;
                            case 13: return point * DexteritySkills.Skill14;
                            case 14: return point * DexteritySkills.Skill15;
                            case 15: return point * DexteritySkills.Skill16;
                            case 16: return point * DexteritySkills.Skill17;
                            case 17: return point * DexteritySkills.Skill18;
                            case 18: return point * DexteritySkills.Skill19;
                            case 19: return point * DexteritySkills.Skill20;
                            case 20: return point * DexteritySkills.Skill21;
                            case 21: return point * DexteritySkills.Skill22;
                            case 22: return point * DexteritySkills.Skill23;
                            case 23: return point * DexteritySkills.Skill24;
                            case 24: return point * DexteritySkills.Skill25;
                            case 25: return point * DexteritySkills.Skill26;
                            case 26: return point * DexteritySkills.Skill27;
                            case 27: return point * DexteritySkills.Skill28;
                            case 28: return point * DexteritySkills.Skill29;
                            case 29: return point * DexteritySkills.Skill30;
                            case 30: return point * DexteritySkills.Skill31;
                            case 31: return point * DexteritySkills.Skill32;
                            case 32: return point * DexteritySkills.Skill33;
                            case 33: return point * DexteritySkills.Skill34;
                            case 34: return point * DexteritySkills.Skill35;
                            case 35: return point * DexteritySkills.Skill36;
                            case 36: return point * DexteritySkills.Skill37;
                            case 37: return point * DexteritySkills.Skill38;
                            case 38: return point * DexteritySkills.Skill39;
                            case 39: return point * DexteritySkills.Skill40;
                            case 40: return point * DexteritySkills.Skill41;
                            case 41: return point * DexteritySkills.Skill42;
                            case 42: return point * DexteritySkills.Skill43;
                            case 43: return point * DexteritySkills.Skill44;
                            case 44: return point * DexteritySkills.Skill45;
                            case 45: return point * DexteritySkills.Skill46;
                            case 46: return point * DexteritySkills.Skill47;
                            case 47: return point * DexteritySkills.Skill48;
                            case 48: return point * DexteritySkills.Skill49;
                            case 49: return point * DexteritySkills.Skill50;
                            case 50: return point * DexteritySkills.Skill51;
                            case 51: return point * DexteritySkills.Skill52;
                            case 52: return point * DexteritySkills.Skill53;
                            case 53: return point * DexteritySkills.Skill54;
                            case 54: return point * DexteritySkills.Skill55;
                            case 55: return point * DexteritySkills.Skill56;
                            case 56: return point * DexteritySkills.Skill57;
                            case 57: return point * DexteritySkills.Skill58;
                            case 58: return point * DexteritySkills.Skill59;
                            case 59: return point * DexteritySkills.Skill60;
                            case 60: return point * DexteritySkills.Skill61;
                            case 61: return point * DexteritySkills.Skill62;
                            case 62: return point * DexteritySkills.Skill63;
                            case 63: return point * DexteritySkills.Skill64;
                            case 64: return point * DexteritySkills.Skill65;
                            case 65: return point * DexteritySkills.Skill66;
                            case 66: return point * DexteritySkills.Skill67;
                            case 67: return point * DexteritySkills.Skill68;
                            case 68: return point * DexteritySkills.Skill69;
                            case 69: return point * DexteritySkills.Skill70;
                            case 70: return point * DexteritySkills.Skill71;
                            case 71: return point * DexteritySkills.Skill72;
                            case 72: return point * DexteritySkills.Skill73;
                            case 73: return point * DexteritySkills.Skill74;
                            case 74: return point * DexteritySkills.Skill75;
                            case 75: return point * DexteritySkills.Skill76;
                            case 76: return point * DexteritySkills.Skill77;
                            case 77: return point * DexteritySkills.Skill78;
                            case 78: return point * DexteritySkills.Skill79;
                            case 79: return point * DexteritySkills.Skill80;
                            case 80: return point * DexteritySkills.Skill81;
                            case 81: return point * DexteritySkills.Skill82;
                            case 82: return point * DexteritySkills.Skill83;
                            case 83: return point * DexteritySkills.Skill84;
                            case 84: return point * DexteritySkills.Skill85;
                            case 85: return point * DexteritySkills.Skill86;
                            case 86: return point * DexteritySkills.Skill87;
                            case 87: return point * DexteritySkills.Skill88;
                            default: return point;
                        }
                    }
                case "Intelligence":
                    {
                        switch (skill)
                        {
                            case 0: return point * IntelligenceSkills.Skill1;
                            case 1: return point * IntelligenceSkills.Skill2;
                            case 2: return point * IntelligenceSkills.Skill3;
                            case 3: return point * IntelligenceSkills.Skill4;
                            case 4: return point * IntelligenceSkills.Skill5;
                            case 5: return point * IntelligenceSkills.Skill6;
                            case 6: return point * IntelligenceSkills.Skill7;
                            case 7: return point * IntelligenceSkills.Skill8;
                            case 8: return point * IntelligenceSkills.Skill9;
                            case 9: return point * IntelligenceSkills.Skill10;
                            case 10: return point * IntelligenceSkills.Skill11;
                            case 11: return point * IntelligenceSkills.Skill12;
                            case 12: return point * IntelligenceSkills.Skill13;
                            case 13: return point * IntelligenceSkills.Skill14;
                            case 14: return point * IntelligenceSkills.Skill15;
                            case 15: return point * IntelligenceSkills.Skill16;
                            case 16: return point * IntelligenceSkills.Skill17;
                            case 17: return point * IntelligenceSkills.Skill18;
                            case 18: return point * IntelligenceSkills.Skill19;
                            case 19: return point * IntelligenceSkills.Skill20;
                            case 20: return point * IntelligenceSkills.Skill21;
                            case 21: return point * IntelligenceSkills.Skill22;
                            case 22: return point * IntelligenceSkills.Skill23;
                            case 23: return point * IntelligenceSkills.Skill24;
                            case 24: return point * IntelligenceSkills.Skill25;
                            case 25: return point * IntelligenceSkills.Skill26;
                            case 26: return point * IntelligenceSkills.Skill27;
                            case 27: return point * IntelligenceSkills.Skill28;
                            case 28: return point * IntelligenceSkills.Skill29;
                            case 29: return point * IntelligenceSkills.Skill30;
                            case 30: return point * IntelligenceSkills.Skill31;
                            case 31: return point * IntelligenceSkills.Skill32;
                            case 32: return point * IntelligenceSkills.Skill33;
                            case 33: return point * IntelligenceSkills.Skill34;
                            case 34: return point * IntelligenceSkills.Skill35;
                            case 35: return point * IntelligenceSkills.Skill36;
                            case 36: return point * IntelligenceSkills.Skill37;
                            case 37: return point * IntelligenceSkills.Skill38;
                            case 38: return point * IntelligenceSkills.Skill39;
                            case 39: return point * IntelligenceSkills.Skill40;
                            case 40: return point * IntelligenceSkills.Skill41;
                            case 41: return point * IntelligenceSkills.Skill42;
                            case 42: return point * IntelligenceSkills.Skill43;
                            case 43: return point * IntelligenceSkills.Skill44;
                            case 44: return point * IntelligenceSkills.Skill45;
                            case 45: return point * IntelligenceSkills.Skill46;
                            case 46: return point * IntelligenceSkills.Skill47;
                            case 47: return point * IntelligenceSkills.Skill48;
                            case 48: return point * IntelligenceSkills.Skill49;
                            case 49: return point * IntelligenceSkills.Skill50;
                            case 50: return point * IntelligenceSkills.Skill51;
                            case 51: return point * IntelligenceSkills.Skill52;
                            case 52: return point * IntelligenceSkills.Skill53;
                            case 53: return point * IntelligenceSkills.Skill54;
                            case 54: return point * IntelligenceSkills.Skill55;
                            case 55: return point * IntelligenceSkills.Skill56;
                            case 56: return point * IntelligenceSkills.Skill57;
                            case 57: return point * IntelligenceSkills.Skill58;
                            case 58: return point * IntelligenceSkills.Skill59;
                            case 59: return point * IntelligenceSkills.Skill60;
                            case 60: return point * IntelligenceSkills.Skill61;
                            case 61: return point * IntelligenceSkills.Skill62;
                            case 62: return point * IntelligenceSkills.Skill63;
                            case 63: return point * IntelligenceSkills.Skill64;
                            case 64: return point * IntelligenceSkills.Skill65;
                            case 65: return point * IntelligenceSkills.Skill66;
                            case 66: return point * IntelligenceSkills.Skill67;
                            case 67: return point * IntelligenceSkills.Skill68;
                            case 68: return point * IntelligenceSkills.Skill69;
                            case 69: return point * IntelligenceSkills.Skill70;
                            case 70: return point * IntelligenceSkills.Skill71;
                            case 71: return point * IntelligenceSkills.Skill72;
                            case 72: return point * IntelligenceSkills.Skill73;
                            case 73: return point * IntelligenceSkills.Skill74;
                            case 74: return point * IntelligenceSkills.Skill75;
                            case 75: return point * IntelligenceSkills.Skill76;
                            case 76: return point * IntelligenceSkills.Skill77;
                            case 77: return point * IntelligenceSkills.Skill78;
                            case 78: return point * IntelligenceSkills.Skill79;
                            case 79: return point * IntelligenceSkills.Skill80;
                            case 80: return point * IntelligenceSkills.Skill81;
                            case 81: return point * IntelligenceSkills.Skill82;
                            case 82: return point * IntelligenceSkills.Skill83;
                            case 83: return point * IntelligenceSkills.Skill84;
                            case 84: return point * IntelligenceSkills.Skill85;
                            case 85: return point * IntelligenceSkills.Skill86;
                            case 86: return point * IntelligenceSkills.Skill87;
                            case 87: return point * IntelligenceSkills.Skill88;
                            default: return point;
                        }
                    }
                case "Wisdom":
                    {
                        switch (skill)
                        {
                            case 0: return point * WisdomSkills.Skill1;
                            case 1: return point * WisdomSkills.Skill2;
                            case 2: return point * WisdomSkills.Skill3;
                            case 3: return point * WisdomSkills.Skill4;
                            case 4: return point * WisdomSkills.Skill5;
                            case 5: return point * WisdomSkills.Skill6;
                            case 6: return point * WisdomSkills.Skill7;
                            case 7: return point * WisdomSkills.Skill8;
                            case 8: return point * WisdomSkills.Skill9;
                            case 9: return point * WisdomSkills.Skill10;
                            case 10: return point * WisdomSkills.Skill11;
                            case 11: return point * WisdomSkills.Skill12;
                            case 12: return point * WisdomSkills.Skill13;
                            case 13: return point * WisdomSkills.Skill14;
                            case 14: return point * WisdomSkills.Skill15;
                            case 15: return point * WisdomSkills.Skill16;
                            case 16: return point * WisdomSkills.Skill17;
                            case 17: return point * WisdomSkills.Skill18;
                            case 18: return point * WisdomSkills.Skill19;
                            case 19: return point * WisdomSkills.Skill20;
                            case 20: return point * WisdomSkills.Skill21;
                            case 21: return point * WisdomSkills.Skill22;
                            case 22: return point * WisdomSkills.Skill23;
                            case 23: return point * WisdomSkills.Skill24;
                            case 24: return point * WisdomSkills.Skill25;
                            case 25: return point * WisdomSkills.Skill26;
                            case 26: return point * WisdomSkills.Skill27;
                            case 27: return point * WisdomSkills.Skill28;
                            case 28: return point * WisdomSkills.Skill29;
                            case 29: return point * WisdomSkills.Skill30;
                            case 30: return point * WisdomSkills.Skill31;
                            case 31: return point * WisdomSkills.Skill32;
                            case 32: return point * WisdomSkills.Skill33;
                            case 33: return point * WisdomSkills.Skill34;
                            case 34: return point * WisdomSkills.Skill35;
                            case 35: return point * WisdomSkills.Skill36;
                            case 36: return point * WisdomSkills.Skill37;
                            case 37: return point * WisdomSkills.Skill38;
                            case 38: return point * WisdomSkills.Skill39;
                            case 39: return point * WisdomSkills.Skill40;
                            case 40: return point * WisdomSkills.Skill41;
                            case 41: return point * WisdomSkills.Skill42;
                            case 42: return point * WisdomSkills.Skill43;
                            case 43: return point * WisdomSkills.Skill44;
                            case 44: return point * WisdomSkills.Skill45;
                            case 45: return point * WisdomSkills.Skill46;
                            case 46: return point * WisdomSkills.Skill47;
                            case 47: return point * WisdomSkills.Skill48;
                            case 48: return point * WisdomSkills.Skill49;
                            case 49: return point * WisdomSkills.Skill50;
                            case 50: return point * WisdomSkills.Skill51;
                            case 51: return point * WisdomSkills.Skill52;
                            case 52: return point * WisdomSkills.Skill53;
                            case 53: return point * WisdomSkills.Skill54;
                            case 54: return point * WisdomSkills.Skill55;
                            case 55: return point * WisdomSkills.Skill56;
                            case 56: return point * WisdomSkills.Skill57;
                            case 57: return point * WisdomSkills.Skill58;
                            case 58: return point * WisdomSkills.Skill59;
                            case 59: return point * WisdomSkills.Skill60;
                            case 60: return point * WisdomSkills.Skill61;
                            case 61: return point * WisdomSkills.Skill62;
                            case 62: return point * WisdomSkills.Skill63;
                            case 63: return point * WisdomSkills.Skill64;
                            case 64: return point * WisdomSkills.Skill65;
                            case 65: return point * WisdomSkills.Skill66;
                            case 66: return point * WisdomSkills.Skill67;
                            case 67: return point * WisdomSkills.Skill68;
                            case 68: return point * WisdomSkills.Skill69;
                            case 69: return point * WisdomSkills.Skill70;
                            case 70: return point * WisdomSkills.Skill71;
                            case 71: return point * WisdomSkills.Skill72;
                            case 72: return point * WisdomSkills.Skill73;
                            case 73: return point * WisdomSkills.Skill74;
                            case 74: return point * WisdomSkills.Skill75;
                            case 75: return point * WisdomSkills.Skill76;
                            case 76: return point * WisdomSkills.Skill77;
                            case 77: return point * WisdomSkills.Skill78;
                            case 78: return point * WisdomSkills.Skill79;
                            case 79: return point * WisdomSkills.Skill80;
                            case 80: return point * WisdomSkills.Skill81;
                            case 81: return point * WisdomSkills.Skill82;
                            case 82: return point * WisdomSkills.Skill83;
                            case 83: return point * WisdomSkills.Skill84;
                            case 84: return point * WisdomSkills.Skill85;
                            case 85: return point * WisdomSkills.Skill86;
                            case 86: return point * WisdomSkills.Skill87;
                            case 87: return point * WisdomSkills.Skill88;
                            default: return point;
                        }
                    }
                case "Charisma":
                    {
                        switch (skill)
                        {
                            case 0: return point * CharismaSkills.Skill1;
                            case 1: return point * CharismaSkills.Skill2;
                            case 2: return point * CharismaSkills.Skill3;
                            case 3: return point * CharismaSkills.Skill4;
                            case 4: return point * CharismaSkills.Skill5;
                            case 5: return point * CharismaSkills.Skill6;
                            case 6: return point * CharismaSkills.Skill7;
                            case 7: return point * CharismaSkills.Skill8;
                            case 8: return point * CharismaSkills.Skill9;
                            case 9: return point * CharismaSkills.Skill10;
                            case 10: return point * CharismaSkills.Skill11;
                            case 11: return point * CharismaSkills.Skill12;
                            case 12: return point * CharismaSkills.Skill13;
                            case 13: return point * CharismaSkills.Skill14;
                            case 14: return point * CharismaSkills.Skill15;
                            case 15: return point * CharismaSkills.Skill16;
                            case 16: return point * CharismaSkills.Skill17;
                            case 17: return point * CharismaSkills.Skill18;
                            case 18: return point * CharismaSkills.Skill19;
                            case 19: return point * CharismaSkills.Skill20;
                            case 20: return point * CharismaSkills.Skill21;
                            case 21: return point * CharismaSkills.Skill22;
                            case 22: return point * CharismaSkills.Skill23;
                            case 23: return point * CharismaSkills.Skill24;
                            case 24: return point * CharismaSkills.Skill25;
                            case 25: return point * CharismaSkills.Skill26;
                            case 26: return point * CharismaSkills.Skill27;
                            case 27: return point * CharismaSkills.Skill28;
                            case 28: return point * CharismaSkills.Skill29;
                            case 29: return point * CharismaSkills.Skill30;
                            case 30: return point * CharismaSkills.Skill31;
                            case 31: return point * CharismaSkills.Skill32;
                            case 32: return point * CharismaSkills.Skill33;
                            case 33: return point * CharismaSkills.Skill34;
                            case 34: return point * CharismaSkills.Skill35;
                            case 35: return point * CharismaSkills.Skill36;
                            case 36: return point * CharismaSkills.Skill37;
                            case 37: return point * CharismaSkills.Skill38;
                            case 38: return point * CharismaSkills.Skill39;
                            case 39: return point * CharismaSkills.Skill40;
                            case 40: return point * CharismaSkills.Skill41;
                            case 41: return point * CharismaSkills.Skill42;
                            case 42: return point * CharismaSkills.Skill43;
                            case 43: return point * CharismaSkills.Skill44;
                            case 44: return point * CharismaSkills.Skill45;
                            case 45: return point * CharismaSkills.Skill46;
                            case 46: return point * CharismaSkills.Skill47;
                            case 47: return point * CharismaSkills.Skill48;
                            case 48: return point * CharismaSkills.Skill49;
                            case 49: return point * CharismaSkills.Skill50;
                            case 50: return point * CharismaSkills.Skill51;
                            case 51: return point * CharismaSkills.Skill52;
                            case 52: return point * CharismaSkills.Skill53;
                            case 53: return point * CharismaSkills.Skill54;
                            case 54: return point * CharismaSkills.Skill55;
                            case 55: return point * CharismaSkills.Skill56;
                            case 56: return point * CharismaSkills.Skill57;
                            case 57: return point * CharismaSkills.Skill58;
                            case 58: return point * CharismaSkills.Skill59;
                            case 59: return point * CharismaSkills.Skill60;
                            case 60: return point * CharismaSkills.Skill61;
                            case 61: return point * CharismaSkills.Skill62;
                            case 62: return point * CharismaSkills.Skill63;
                            case 63: return point * CharismaSkills.Skill64;
                            case 64: return point * CharismaSkills.Skill65;
                            case 65: return point * CharismaSkills.Skill66;
                            case 66: return point * CharismaSkills.Skill67;
                            case 67: return point * CharismaSkills.Skill68;
                            case 68: return point * CharismaSkills.Skill69;
                            case 69: return point * CharismaSkills.Skill70;
                            case 70: return point * CharismaSkills.Skill71;
                            case 71: return point * CharismaSkills.Skill72;
                            case 72: return point * CharismaSkills.Skill73;
                            case 73: return point * CharismaSkills.Skill74;
                            case 74: return point * CharismaSkills.Skill75;
                            case 75: return point * CharismaSkills.Skill76;
                            case 76: return point * CharismaSkills.Skill77;
                            case 77: return point * CharismaSkills.Skill78;
                            case 78: return point * CharismaSkills.Skill79;
                            case 79: return point * CharismaSkills.Skill80;
                            case 80: return point * CharismaSkills.Skill81;
                            case 81: return point * CharismaSkills.Skill82;
                            case 82: return point * CharismaSkills.Skill83;
                            case 83: return point * CharismaSkills.Skill84;
                            case 84: return point * CharismaSkills.Skill85;
                            case 85: return point * CharismaSkills.Skill86;
                            case 86: return point * CharismaSkills.Skill87;
                            case 87: return point * CharismaSkills.Skill88;
                            default: return point;
                        }
                    }
                    default: return point;
            }
        }
    }
}
